import { StyleSheet } from "react-native";

export const tripStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f5f5f5" },
  container: { padding: 20 },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20
  },
  titleWithBackContainer:{ 
    flexDirection: "row", 
    alignItems: "center", 
    marginBottom: 20 
  },
  title: { fontSize: 24, fontWeight: "bold",  },
  titleLabel: { fontSize: 18, fontWeight: "bold",  },
  label: { fontSize: 16, marginBottom: 5 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  button: {
    marginTop: 10,
    padding: 12,
    backgroundColor: "#007AFF",
    borderRadius: 8,
    alignItems: "center",
  },
  buttonText: { color: "white", fontWeight: "bold" },
  sectionTitle: { fontSize: 18, fontWeight: "bold", marginVertical: 10 },
  friendItem: {
    padding: 10,
    backgroundColor: "white",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  listContainer: { 
    padding: 15,
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 8,
  },
  card: {
    padding: 12,
    marginVertical: 5,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 8,
    backgroundColor: "white",
  },
  cardText: {
    fontSize: 18,
    color: "#333",
    marginVertical: 2,
  },
  cardActivity: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    marginVertical: 2,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    margin: 20,
    padding: 20,
    borderRadius: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: "white",
  },
  deleteBtn: {
    padding: 8,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
  fab: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "blue",
    width: 50,
    height: 50,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5, // android shadow
    shadowColor: "black", // ios shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
    overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  paidByButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    marginRight: 8,
    borderRadius: 6,
  },
  splitRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  cancelButton: {
    marginTop: 10,
    padding: 12,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "#eee",
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
});